# NODE_MAILER CONFIG FOR MAGIC LINKS
EMAIL_SERVICE="Gmail"
EMAIL_HOST="smtp.gmail.com"
EMAIL_PORT="465"
EMAIL_USER="user@gmail.com"
EMAIL_APP_PASS="abcd efgh ijkl mnop"
# GOOGLE CONFIG FOR GOOGLE FEDERATED IDENTITY
GOOGLE_CLIENT_ID="#####-#######.apps.googleusercontent.com"
# META CONFIG FOR META FEDERATED IDENTITY
FACEBOOK_APP_ID="123456789101212131"
FACEBOOK_SECRET="abcd efgh ijkl mnop"
