PROJECT_NAME="SvelteKit SST Auth"
DEV_DOMAIN_NAME="https://localhost:3000"
PROD_DOMAIN_NAME="https://skits.michaelcuneo.com.au"
HOSTED_ZONE_NAME="michaelcuneo.com.au"
API_DOMAIN_NAME="https://skitsapi.michaelcuneo.com.au"
VERSION="1.0.0"